using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace HW2
{
    //This class was created by winform. Output a TextBox
    public partial class Form1 : Form
    {
        //Constructor for Form1
        public Form1()
        {
            InitializeComponent();
            RunDistinctIntegers();
        }
        //Auto generated by winform
        private void Form1_Load(object sender, EventArgs e)
        {

        }



        //Run DistinctIntegersOne,DistinctIntegersTwo,DistinctIntegersThree
        //Output the resolts to the textBox
        private void RunDistinctIntegers() // this is your method
        {



            DistinctIntegers obj1 = new DistinctIntegers();
            int resOne = obj1.DistinctIntegersOne();
            int resTwo = obj1.DistinctIntegersTwo();
            int resThree = obj1.DistinctIntegersThree(); 




            //This will update the Textbox
            lblHelloWorld3.Text = "1. Hash Set method: " + resOne + " unique numbers" + Environment.NewLine +
                "Here you will have info about the time complexity of your code" + Environment.NewLine +
                "You also need info about how you determined it" + Environment.NewLine +
                "2. O(1) storage method: " + resTwo + " unique numbers" + Environment.NewLine +
                "3. Sorted method: " + resThree + " unique numbers";










        }
        //Auto generated by winform
        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }
    }
}
